import React, { useState, useEffect, useCallback } from 'react';
import { View, Text, StyleSheet, TouchableOpacity, ActivityIndicator, Alert } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { useAuth } from '../../app/_contexts/auth-context';
import { useData } from '../../app/_contexts/data-context'; // To get access to addTPath, etc.
import Toast from 'react-native-toast-message';
import { Colors, Spacing, BorderRadius } from '../../constants/Theme';
import type { Gym, DashboardProfile, TPath } from '@data/storage/models'; // Assuming these types are available

interface SetupGymPlanPromptProps {
  gym: Gym;
  onSetupSuccess: () => void;
  profile: DashboardProfile | null;
  setTempStatusMessage: (message: { message: string; type: 'added' | 'removed' | 'success' | 'error' } | null) => void;
}

// Placeholder for CopyGymSetupDialog (will be implemented later if needed)
const CopyGymSetupDialog = ({ open, onOpenChange, targetGym, sourceGyms, onCopySuccess, setTempStatusMessage }: any) => {
  if (!open) return null;

  const handleCopy = () => {
    Alert.alert(
      'Copy from another Gym',
      'This is a placeholder. In a real implementation, you would select a source gym and copy its T-Paths/workouts.',
      [
        { text: 'Cancel', style: 'cancel' },
        { text: 'Simulate Copy', onPress: () => {
          onCopySuccess();
          onOpenChange(false);
          Toast.show({ type: 'success', text1: 'Simulated copying gym setup.' });
        } },
      ]
    );
  };

  return (
    <View style={styles.modalOverlay}>
      <View style={styles.modalContent}>
        <Text style={styles.modalTitle}>Copy Gym Setup to {targetGym.name}</Text>
        {sourceGyms.length > 0 ? (
          <Text style={styles.textMuted}>Select a gym to copy from...</Text>
        ) : (
          <Text style={styles.textMuted}>No other gyms available to copy from.</Text>
        )}
        <TouchableOpacity onPress={handleCopy} style={styles.button} disabled={sourceGyms.length === 0}>
          <Text style={styles.buttonText}>Copy (Placeholder)</Text>
        </TouchableOpacity>
        <TouchableOpacity onPress={() => onOpenChange(false)} style={styles.buttonSecondary}>
          <Text style={styles.buttonSecondaryText}>Cancel</Text>
        </TouchableOpacity>
      </View>
    </View>
  );
};

export const SetupGymPlanPrompt = ({ gym, onSetupSuccess, profile, setTempStatusMessage }: SetupGymPlanPromptProps) => {
  const { userId } = useAuth();
  const { addTPath } = useData(); // Assuming addTPath is available in DataContext
  const [isCopyDialogOpen, setIsCopyDialogOpen] = useState(false);
  const [sourceGyms, setSourceGyms] = useState<Gym[]>([]); // This would be fetched from useGym
  const [loading, setLoading] = useState(false);

  // For mobile, sourceGyms would come from useGym().userGyms, filtered to exclude the current gym
  useEffect(() => {
    // Simulate fetching other gyms for now
    // In a real scenario, you'd get this from the GymContext or a data hook
    // For this placeholder, we'll just assume there are no other gyms to copy from.
    setSourceGyms([]); 
  }, [gym.id]);

  const handleSetupDefaults = async () => {
    if (!userId) {
      setTempStatusMessage({ message: "Error: User not authenticated.", type: 'error' });
      return;
    }
    setLoading(true);
    try {
      // Simulate setting up default T-Path and workouts
      // In a real implementation, this would involve creating default T-Paths and linking them to the gym
      const defaultTPath: TPath = {
        id: `default-tpath-${gym.id}`,
        user_id: userId,
        template_name: `Default Program for ${gym.name}`,
        description: 'A basic workout program generated by the app.',
        is_main_program: true,
        parent_t_path_id: null,
        order_index: 0,
        is_ai_generated: true,
        ai_generation_params: null,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
        gym_id: gym.id, // Link to the current gym
      };

      await addTPath(defaultTPath); // Add the default TPath
      
      // Simulate adding some default child workouts to the TPath
      // This is a simplified example; actual implementation would be more robust.
      const defaultWorkout1: TPath = {
        id: `default-workout-1-${gym.id}`,
        user_id: userId,
        template_name: 'Push Workout A',
        description: 'Focus on chest, shoulders, and triceps.',
        is_main_program: false,
        parent_t_path_id: defaultTPath.id,
        order_index: 0,
        is_ai_generated: true,
        ai_generation_params: null,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
        gym_id: gym.id,
      };

      const defaultWorkout2: TPath = {
        id: `default-workout-2-${gym.id}`,
        user_id: userId,
        template_name: 'Pull Workout A',
        description: 'Focus on back and biceps.',
        is_main_program: false,
        parent_t_path_id: defaultTPath.id,
        order_index: 1,
        is_ai_generated: true,
        ai_generation_params: null,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
        gym_id: gym.id,
      };
      await addTPath(defaultWorkout1);
      await addTPath(defaultWorkout2);

      setTempStatusMessage({ message: "Default gym plan set up successfully!", type: 'success' });
      onSetupSuccess(); // Trigger a refresh of the parent data
    } catch (err: any) {
      console.error("Failed to set up default gym plan:", err.message);
      setTempStatusMessage({ message: err.message || "Failed to set up default gym plan.", type: 'error' });
    } finally {
      setLoading(false);
    }
  };

  return (
    <View style={styles.cardContainer}>
      <View style={styles.cardHeader}>
        <Ionicons name="warning-outline" size={24} color={Colors.warning} style={styles.icon} />
        <View>
          <Text style={styles.cardTitle}>Setup Required for "{gym.name}"</Text>
          <Text style={styles.cardDescription}>This gym has no workout plan. Choose an option below to get started.</Text>
        </View>
      </View>
      <View style={styles.cardContent}>
        <TouchableOpacity onPress={handleSetupDefaults} style={styles.button} disabled={loading}>
          {loading ? (
            <ActivityIndicator color={Colors.primaryForeground} />
          ) : (
            <>
              <Ionicons name="sparkles-outline" size={16} color={Colors.primaryForeground} style={styles.buttonIcon} />
              <Text style={styles.buttonText}>Use App Defaults</Text>
            </>
          )}
        </TouchableOpacity>
        <TouchableOpacity
          onPress={() => setIsCopyDialogOpen(true)}
          style={[styles.button, styles.outlineButton]}
          disabled={sourceGyms.length === 0 || loading}
        >
          <Ionicons name="copy-outline" size={16} color={Colors.primary} style={styles.buttonIcon} />
          <Text style={[styles.buttonText, styles.outlineButtonText]}>Copy from another Gym</Text>
        </TouchableOpacity>
      </View>
      <CopyGymSetupDialog
        open={isCopyDialogOpen}
        onOpenChange={setIsCopyDialogOpen}
        targetGym={gym}
        sourceGyms={sourceGyms}
        onCopySuccess={onSetupSuccess}
        setTempStatusMessage={setTempStatusMessage}
      />
    </View>
  );
};

const styles = StyleSheet.create({
  cardContainer: {
    backgroundColor: Colors.card,
    borderRadius: BorderRadius.lg,
    padding: Spacing.md,
    marginVertical: Spacing.sm,
    borderWidth: 1,
    borderColor: Colors.warningBorder, // Using a warning specific border color
  },
  cardHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: Spacing.sm,
  },
  icon: {
    marginRight: Spacing.sm,
  },
  cardTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: Colors.warningText,
  },
  cardDescription: {
    fontSize: 14,
    color: Colors.warningText,
    marginTop: Spacing.xs,
  },
  cardContent: {
    flexDirection: 'column',
    gap: Spacing.sm,
    marginTop: Spacing.md,
  },
  button: {
    backgroundColor: Colors.primary,
    paddingVertical: Spacing.sm,
    paddingHorizontal: Spacing.md,
    borderRadius: BorderRadius.md,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
  },
  buttonText: {
    color: Colors.primaryForeground,
    fontSize: 16,
    fontWeight: '600',
    marginLeft: Spacing.xs,
  },
  buttonIcon: {
    marginRight: Spacing.xs,
  },
  outlineButton: {
    backgroundColor: 'transparent',
    borderWidth: 1,
    borderColor: Colors.primary,
  },
  outlineButtonText: {
    color: Colors.primary,
  },
  modalOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 1000, // Ensure modal is on top
  },
  modalContent: {
    backgroundColor: Colors.background,
    borderRadius: BorderRadius.lg,
    padding: Spacing.lg,
    width: '90%',
    maxWidth: 400,
    alignItems: 'center',
  },
  modalTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: Colors.foreground,
    marginBottom: Spacing.md,
    textAlign: 'center',
  },
  modalText: {
    fontSize: 16,
    color: Colors.textMuted,
    marginBottom: Spacing.md,
    textAlign: 'center',
  },
  buttonSecondary: {
    backgroundColor: Colors.secondary,
    paddingVertical: Spacing.sm,
    paddingHorizontal: Spacing.md,
    borderRadius: BorderRadius.md,
    alignItems: 'center',
    marginTop: Spacing.sm,
  },
  buttonSecondaryText: {
    color: Colors.secondaryForeground,
    fontSize: 16,
    fontWeight: '600',
  },
});
