import { Json } from "../json";

export type ProfilesRow = {
  body_fat_pct: number | null;
  created_at: string | null;
  default_rest_time_seconds: number | null;
  first_name: string | null;
  full_name: string | null;
  health_notes: string | null;
  height_cm: number | null;
  id: string;
  last_ai_coach_use_at: string | null;
  last_name: string | null;
  preferred_distance_unit: string | null;
  preferred_muscles: string | null;
  preferred_weight_unit: string | null;
  primary_goal: string | null;
  target_date: string | null;
  updated_at: string | null;
  preferred_session_length: string | null;
  active_t_path_id: string | null;
  weight_kg: number | null;
};
export type ProfilesInsert = {
  body_fat_pct?: number | null;
  created_at?: string | null;
  default_rest_time_seconds?: number | null;
  first_name?: string | null;
  full_name?: string | null;
  health_notes?: string | null;
  height_cm?: number | null;
  id: string;
  last_ai_coach_use_at?: string | null;
  last_name?: string | null;
  preferred_distance_unit?: string | null;
  preferred_muscles?: string | null;
  preferred_weight_unit?: string | null;
  primary_goal?: string | null;
  target_date?: string | null;
  updated_at?: string | null;
  weight_kg?: number | null;
  preferred_session_length?: string | null;
  active_t_path_id?: string | null;
};
export type ProfilesUpdate = {
  body_fat_pct?: number | null;
  created_at?: string | null;
  default_rest_time_seconds?: number | null;
  first_name?: string | null;
  full_name?: string | null;
  health_notes?: string | null;
  height_cm?: number | null;
  id?: string;
  last_ai_coach_use_at?: string | null;
  last_name?: string | null;
  preferred_distance_unit?: string | null;
  preferred_muscles?: string | null;
  preferred_weight_unit?: string | null;
  primary_goal?: string | null;
  target_date?: string | null;
  updated_at?: string | null;
  weight_kg?: number | null;
  preferred_session_length?: string | null;
  active_t_path_id?: string | null;
};